version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    container_name: db_restaur

    command: -p 2112
    expose:
      - 2112
    env_file:
      - .env
    networks:
      - common_network


  redis-cache:
    image: redis:7
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - common_network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
    networks:
      - common_network

  celery:
    build:
      context: .
    container_name: celery_app
    env_file:
      - .env
    command: sh -c "cd src && sleep 20 && celery --app=tasks.tasks.celery_app worker -B"
    networks:
      - common_network
    depends_on:
      - rabbitmq


  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: sh -c "sleep 2 && alembic upgrade head && cd src && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - common_network
    depends_on:
      - db
      - redis-cache
      - rabbitmq
      - celery


networks:
  common_network:
