version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    container_name: db_restaur
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: -p 2112
    expose:
      - 2112
    env_file:
      - .env
    networks:
      - common_network

  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/app.sh"]
    ports:
      - 8000:8000
    networks:
      - common_network
    depends_on:
      - db


volumes:
  postgres_data:
networks:
  common_network: